name: meadow
description: Provides a selection of easy-to-use form field widgets to be used within a Flutter form
version: 0.0.2
author: Samuel Freeman <freeman@easesoftware.co.uk>
homepage: https://github.com/Sam-Freeman/Meadow
publish_to: https://pub.dartlang.org
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

